name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk with Gradle
      run: ./gradlew clean && ./gradlew app:assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: 添加朋友
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
        # The desired behavior if no files are found using the provided path.

    - name: Upload File to Pgyer
      run: curl -F 'file=@${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk' -F "_api_key=${{ secrets.PGYER_API_KEY }}" -F "uKey=${{ secrets.PGYER_USER_KEY }}" -F "buildInstallType=3" https://www.pgyer.com/apiv2/app/upload

