# You may pin to the exact commit or the version.
# uses: anc95/ChatGPT-CodeReview@a245376b017f5a22be59b27af50e2a66c55cf65e
uses: anc95/ChatGPT-CodeReview@v1.0.4

name: Code Review

permissions:
  contents: read
  push: write

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese
